name: Derin Bulten Otopilot

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı otomatik çalışır
  workflow_dispatch:

jobs:
  calistir:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Kutuphaneleri Yukle
        run: pip install requests

      - name: Bulteni Firlat
        run: python bulten.py
