name: Toplu Haber Botu

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı otomatik tetiklenir
  workflow_dispatch:      # İstediğin an elle test edebilmen için

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari cek
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
            python-version: '3.10'

      - name: Botu calistir
        run: python bot.py
        
